import CustomerGridList from './CustomerGridList'
import {CUSTOMER_CREATE_DIALOG_OPEN} from './CustomerCreateDialog'
import {CUSTOMER_FILTER_KEY, CUSTOMER_FILTER_OPEN} from './CustomerFilterForm'

const CUSTOMER_DELETE_DIALOG_OPEN = 'openDeleteDialog'
const CUSTOMER_UPDATE_DIALOG_OPEN = 'openUpdateDialog'
const CUSTOMER_MAIL_DIALOG_OPEN = 'openMailDialog'
export {
  CUSTOMER_CREATE_DIALOG_OPEN,
  CUSTOMER_UPDATE_DIALOG_OPEN,
  CUSTOMER_DELETE_DIALOG_OPEN,
  CUSTOMER_FILTER_KEY,
  CUSTOMER_FILTER_OPEN,
  CUSTOMER_MAIL_DIALOG_OPEN,
  CustomerGridList
}
