export const SIGN_IN = 'SIGN_IN'
export const AUTH_CONFIRM = 'AUTH_CONFIRM'

export const CONFIG = 'CONFIG'

export const USERS_LIST = 'USERS_LIST'
export const USERS_ITEM = 'USERS_ITEM'
export const USERS_UPDATE = 'USERS_UPDATE'
export const USERS_CREATE = 'USERS_CREATE'
export const USERS_DELETE = 'USERS_DELETE'
export const USERS_GROUP = 'USERS_GROUP'
export const SPHERES_LIST = 'SPHERES_LIST'

export const CLIENT_LIST = 'CLIENT_LIST'
export const CLIENT_LIST_REPETITION = 'CLIENT_LIST_REPETITION'
export const CLIENT_ITEM = 'CLIENT_ITEM'
export const CLIENT_ITEM_REPETITION = 'CLIENT_ITEM_REPETITION'
export const CLIENT_CONTACTS = 'CLIENT_CONTACTS'
export const CLIENT_UPDATE = 'CLIENT_UPDATE'
export const CLIENT_CREATE = 'CLIENT_CREATE'
export const CLIENT_DELETE = 'CLIENT_DELETE'

export const SNACKBAR = 'SNACKBAR'
export const SNACKBAR_OPEN = `${SNACKBAR}_OPEN`
export const SNACKBAR_CLOSE = `${SNACKBAR}_CLOSE`

export const ERROR = 'ERROR'
export const ERROR_OPEN = `${ERROR}_OPEN`
export const ERROR_CLOSE = `${ERROR}_CLOSE`

export const NOTIFICATIONS_LIST = 'NOTIFICATIONS_LIST'
export const NOTIFICATIONS_ITEM = 'NOTIFICATIONS_ITEM'
export const NOTIFICATIONS_DELETE = 'NOTIFICATIONS_DELETE'
export const NOTIFICATIONS_UPDATE = 'NOTIFICATIONS_UPDATE'
export const NOTIFICATIONS_GET_COUNT = 'NOTIFICATIONS_GET_COUNT'

export const ROLE_LIST = 'ROLE_LIST'
export const ROLE_ITEM = 'ROLE_ITEM'
export const ROLE_UPDATE = 'ROLE_UPDATE'
export const ROLE_COURSE_CREATE = 'ROLE_COURSE_CREATE'
export const ROLE_CREATE = 'ROLE_CREATE'
export const ROLE_DELETE = 'ROLE_DELETE'
export const ROLE_PRIMARY = 'ROLE_PRIMARY'
export const ROLE_PRIMARY_UPDATE = 'ROLE_PRIMARY_UPDATE'
export const ROLE_PERMISSION = 'ROLE_PERMISSION'

export const ARTICLES_LIST = 'ARTICLES_LIST'
export const ARTICLES_ITEM = 'ARTICLES_ITEM'
export const ARTICLES_UPDATE = 'ARTICLES_UPDATE'
export const ARTICLES_CREATE = 'ARTICLES_CREATE'
export const ARTICLES_DELETE = 'ARTICLES_DELETE'

export const REESTR_LIST = 'REESTR_LIST'
export const REESTR_ITEM = 'REESTR_ITEM'
export const REESTR_UPDATE = 'REESTR_UPDATE'
export const REESTR_CREATE = 'REESTR_CREATE'
export const REESTR_DELETE = 'REESTR_DELETE'

export const COMPANIES_LIST = 'COMPANIES_LIST'
export const COMPANIES_ITEM = 'COMPANIES_ITEM'
export const COMPANIES_UPDATE = 'COMPANIES_UPDATE'
export const COMPANIES_CREATE = 'COMPANIES_CREATE'
export const COMPANIES_DELETE = 'COMPANIES_DELETE'

export const SKILLS_LIST = 'SKILLS_LIST'
export const SKILLS_ITEM = 'SKILLS_ITEM'
export const SKILLS_UPDATE = 'SKILLS_UPDATE'
export const SKILLS_CREATE = 'SKILLS_CREATE'
export const SKILLS_DELETE = 'SKILLS_DELETE'

export const REGIONS_LIST = 'REGIONS_LIST'
export const REGIONS_ITEM = 'REGIONS_ITEM'
export const REGIONS_UPDATE = 'REGIONS_UPDATE'
export const REGIONS_CREATE = 'REGIONS_CREATE'
export const REGIONS_DELETE = 'REGIONS_DELETE'

export const LANGUAGES_LIST = 'LANGUAGES_LIST'
export const LANGUAGES_ITEM = 'LANGUAGES_ITEM'
export const LANGUAGES_UPDATE = 'LANGUAGES_UPDATE'
export const LANGUAGES_CREATE = 'LANGUAGES_CREATE'
export const LANGUAGES_DELETE = 'LANGUAGES_DELETE'

export const POSITIONS_LIST = 'POSITIONS_LIST'
export const POSITIONS_ITEM = 'POSITIONS_ITEM'
export const POSITIONS_UPDATE = 'POSITIONS_UPDATE'
export const POSITIONS_CREATE = 'POSITIONS_CREATE'
export const POSITIONS_DELETE = 'POSITIONS_DELETE'

/*
*
*
*/

export const HR_APPLICATION_LIST = 'HR_APPLICATION_LIST'
export const HR_APPLICATION_ITEM = 'HR_APPLICATION_ITEM'
export const HR_APPLICATION_UPDATE = 'HR_APPLICATION_UPDATE'
export const HR_APPLICATION_CREATE = 'HR_APPLICATION_CREATE'
export const HR_APPLICATION_DELETE = 'HR_APPLICATION_DELETE'
export const HR_APP_CHANGE_ACTION = 'HR_APP_CHANGE_ACTION'

export const HR_APP_GET_MEETING_LIST = 'HR_APP_GET_MEETING_LIST'
export const HR_APP_UPDATE_MEETING = 'HR_APP_UPDATE_MEETING'
export const HR_APP_CREATE_MEETING_MULTI = 'HR_APP_CREATE_MEETING_MULTI'
export const HR_APP_COMPLETE = 'HR_APP_COMPLETE'

export const HR_PRIVILEGE_LIST = 'HR_PRIVILEGE_LIST'

export const HR_RESUME_LIST = 'HR_RESUME_LIST'
export const HR_RESUME_ITEM = 'HR_RESUME_ITEM'
export const HR_RESUME_UPDATE = 'HR_RESUME_UPDATE'
export const HR_RESUME_CREATE = 'HR_RESUME_CREATE'
export const HR_RESUME_DELETE = 'HR_RESUME_DELETE'

export const HR_LONG_LIST_CREATE = 'HR_LONG_LIST_CREATE'
export const HR_REPORT_LIST_CREATE = 'HR_REPORT_LIST_CREATE'
export const HR_RESUME_PREVIEW_LIST = 'HR_RESUME_PREVIEW_LIST'

export const HR_LONG_LIST = 'HR_LONG_LIST'
export const HR_INTERVIEW_LIST = 'HR_INTERVIEW_LIST'
export const HR_SHORT_LIST = 'HR_SHORT_LIST'
export const HR_SHORT_LIST_CREATE = 'HR_SHORT_LIST_CREATE'
export const HR_REPORT_LIST = 'HR_REPORT_LIST'

export const HR_RESUME_MOVE = 'HR_RESUME_MOVE'
export const HR_RESUME_REMOVE = 'HR_RESUME_REMOVE'
export const HR_FORM_REPORT_LIST = 'HR_FORM_REPORT_LIST'

export const HR_RESUME_COMMENT_CREATE = 'HR_RESUME_COMMENT_CREATE'
export const HR_RESUME_COMMENT_LIST = 'HR_RESUME_COMMENT_LIST'
export const HR_RESUME_NOTE_CREATE = 'HR_RESUME_NOTE_CREATE'

export const HR_APPLICATION_QUESTIONS_CREATE = 'HR_APPLICATION_QUESTIONS_CREATE'
export const HR_APPLICATION_QUESTIONS_LIST = 'HR_APPLICATION_QUESTIONS_LIST'

export const HR_RESUME_ANSWERS_CREATE = 'HR_RESUME_ANSWERS_CREATE'
export const HR_RESUME_ANSWERS_LIST = 'HR_RESUME_ANSWERS_LIST'

export const HR_APP_LOGS_LIST = 'HR_APP_LOGS_LIST'
export const HR_RESUME_ITEM_LOGS = 'HR_RESUME_ITEM_LOGS'
export const HR_APPLICATION_ITEM_STAT = 'HR_APPLICATION_ITEM_STAT'

export const HR_CALENDAR_LIST = 'HR_CALENDAR_LIST'

export const HR_FEEDBACK_CREATE = 'HR_FEEDBACK_CREATE'
export const HR_FEEDBACK_LIST = 'HR_FEEDBACK_LIST'

export const HR_ORDER_SERVICE_LIST = 'HR_ORDER_SERVICE_LIST'

export const POST_LIST = 'POST_LIST'
export const POST_ITEM = 'POST_ITEM'
export const POST_UPDATE = 'POST_UPDATE'
export const POST_CREATE = 'POST_CREATE'
export const POST_DELETE = 'POST_DELETE'

export const COMPANY_TYPE_LIST = 'COMPANY_TYPE_LIST'
export const COMPANY_TYPE_H_LIST = 'COMPANY_TYPE_H_LIST'
export const COMPANY_TYPE_ITEM = 'COMPANY_TYPE_ITEM'
export const COMPANY_TYPE_UPDATE = 'COMPANY_TYPE_UPDATE'
export const COMPANY_TYPE_CREATE = 'COMPANY_TYPE_CREATE'
export const COMPANY_TYPE_DELETE = 'COMPANY_TYPE_DELETE'

export const APPLICANT_LIST = 'APPLICANT_LIST'
export const APPLICANT_ITEM = 'APPLICANT_ITEM'
export const APPLICANT_UPDATE = 'APPLICANT_UPDATE'
export const APPLICANT_CREATE = 'APPLICANT_CREATE'
export const APPLICANT_DELETE = 'APPLICANT_DELETE'
export const APPLICANT_GROUP = 'APPLICANT_GROUP'

export const CUSTOMER_LIST = 'CUSTOMER_LIST'
export const CUSTOMER_ITEM = 'CUSTOMER_ITEM'
export const CUSTOMER_UPDATE = 'CUSTOMER_UPDATE'
export const CUSTOMER_CREATE = 'CUSTOMER_CREATE'
export const CUSTOMER_DELETE = 'CUSTOMER_DELETE'

export const ORDER_LIST = 'ORDER_LIST'
export const ORDER_ITEM = 'ORDER_ITEM'
export const ORDER_UPDATE = 'ORDER_UPDATE'
export const ORDER_CREATE = 'ORDER_CREATE'
export const ORDER_DELETE = 'ORDER_DELETE'

export const PLAN_LIST = 'PLAN_LIST'
export const PLAN_LIST_REPETITION = 'PLAN_LIST_REPETITION'
export const PLAN_ITEM = 'PLAN_ITEM'
export const PLAN_ITEM_REPETITION = 'PLAN_ITEM_REPETITION'
export const PLAN_CONTACTS = 'PLAN_CONTACTS'
export const PLAN_UPDATE = 'PLAN_UPDATE'
export const PLAN_CREATE = 'PLAN_CREATE'
export const PLAN_DELETE = 'PLAN_DELETE'

export const JOB_SEARCH_LIST = 'JOB_SEARCH_LIST'
export const JOB_SEARCH_H_LIST = 'JOB_SEARCH_H_LIST'
export const JOB_SEARCH_ITEM = 'JOB_SEARCH_ITEM'
export const JOB_SEARCH_UPDATE = 'JOB_SEARCH_UPDATE'
export const JOB_SEARCH_CREATE = 'JOB_SEARCH_CREATE'
export const JOB_SEARCH_DELETE = 'JOB_SEARCH_DELETE'

export const PROJECT_LIST = 'PROJECT_LIST'
export const PROJECT_ITEM = 'PROJECT_ITEM'
export const PROJECT_UPDATE = 'PROJECT_UPDATE'
export const PROJECT_CREATE = 'PROJECT_CREATE'
export const PROJECT_DELETE = 'PROJECT_DELETE'

export const SERVICE_LIST = 'SERVICE_LIST'
export const SERVICE_ITEM = 'SERVICE_ITEM'
export const SERVICE_UPDATE = 'SERVICE_UPDATE'
export const SERVICE_CREATE = 'SERVICE_CREATE'
export const SERVICE_DELETE = 'SERVICE_DELETE'

export const TASK_LIST = 'TASK_LIST'
export const TASK_ITEM = 'TASK_ITEM'
export const TASK_UPDATE = 'TASK_UPDATE'
export const TASK_CREATE = 'TASK_CREATE'
export const TASK_DELETE = 'TASK_DELETE'

export const COMMENT_LIST = 'COMMENT_LIST'
export const COMMENT_ITEM = 'COMMENT_ITEM'
export const COMMENT_UPDATE = 'COMMENT_UPDATE'
export const COMMENT_CREATE = 'COMMENT_CREATE'
export const COMMENT_DELETE = 'COMMENT_DELETE'
