export const TOKEN_KEY = 'token'
export const USER_GROUPS = 'user_groups'
export const IS_SUPERUSER = 'is_superuser'
export const PAGE_SIZE = 'page_size'
export const LANGUAGE = 'language'
export const API_HOST = 'api_host'
